sequence_len: 40
in_channels: 1
out_channels: 16
kernel_size: 33
lr: 5.752066213864577e-06
momentum: 0.8595221296407815
weight_decay: 0.008076572325551007
stock: nvda
feature_set:
- log_return
batch_size: 128
dataset_len: 5
horizon: 5
target_var: log_return_forecast
