model_name: lstm_lly
fset_name: close
model:
  class_path: src.models.LSTM_Lightning.model.StockPricePredictor
  init_args:
    sequence_len: 20
    hidden_dim: 64
    num_layers: 1
    lr: 0.001
    dropout: 0
data:
  class_path: src.models.LSTM_Lightning.data.StockDataModule
  init_args:
    stock: "lly"
    feature_set: ['Close']
    sequence_len: 20
    batch_size: 64
    permute_column: null
    dataset_len: 5
    horizon: 5 

