sequence_len: 20
in_channels: 1
out_channels: 64
kernel_size: 11
lr: 3.1857905675449e-05
momentum: 0.9986047140504237
weight_decay: 2.1894956235136965e-05
stock: nvda
feature_set:
- log_return
batch_size: 128
dataset_len: 20
horizon: 5
target_var: log_return_forecast
