sequence_len: 40
in_channels: 1
out_channels: 16
kernel_size: 24
lr: 6.519794866655158e-05
momentum: 0.5524470846875795
weight_decay: 1.1636687917916751e-05
stock: nvda
feature_set:
- log_return
batch_size: 64
dataset_len: 5
horizon: 5
target_var: log_return_forecast
