sequence_len: 10
in_channels: 1
out_channels: 64
kernel_size: 9
lr: 0.0012920381200269117
momentum: 0.6175720382483618
weight_decay: 3.196172368119917e-06
stock: nvda
feature_set:
- log_return
batch_size: 64
dataset_len: 20
horizon: 5
target_var: log_return_forecast
