model:
   name : 'linear'

# Logging and output parameters
mlflow:
  experiment_name: 'linear_tuning'

hyperparameter_tuning:
  features: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'log_open', 'log_high', 'log_low', 'log_close', 'log_volume  ',
       'Close Forecast', 'close_t-1', 'close_t-2', 'close_t-3', 'close_t-4',
       'close_t-5', 'pct_change', 'log_return', 'dayofweek', 'quarter',
       'month', 'year', 'dayofyear', 'dayofmonth', 'weekofyear', 'upper_band',
       'middle_band', 'lower_band', 'SMA_10', 'SMA_20', 'SMA_50', 'EMA_10',
       'EMA_20', 'EMA_50', 'ADX', 'aroon_down', 'aroon_up', 'macd',
       'macdsignal', 'macdhist', 'RSI_14', 'slow_k', 'slow_d', 'williams_r',
       'AD', 'OBV', 'NATR', 'TRANGE', 'fed_funds_rate', 'log_fed_funds_rate',
       '^N225', 'log_^N225', '^IXIC', 'log_^IXIC', '^FTSE', 'log_^FTSE',
       '^SPX', 'log_^SPX', '^DJI', 'log_^DJI']