# Configuration file for model
# ------------------------------
# Data parameters
model:
   hidden_dim: 64
   num_layers: 3
   horizon: 2
   dropout: 0.0

data:
  features: ['Open', 'High', 'Low', 'Close', 'Volume']
  sequence_len: 5
  stock: "brk-b"
  dataset_len: 5

training:
  batch_size: 64
  num_epochs: 30
  lr: 0.001

logging:
  experiment_name: "lstm"

hyperparameter_tuning:
  batch_size: [128]
  num_epochs: [20]
  lr: [0.001]
  sequence_len: [10]
  hidden_dim: [64]
  num_layers: [8, 16]