# Configuration file for model
# ------------------------------
# Data parameters
model:
   hidden_dim: 64
   num_layers: 2

data:
  features: ['Close', 'Open', 'High', 'Low', 'Volume']
  sequence_len: 30

# Training parameters
training:
  batch_size: 64
  num_epochs: 50
  lr: 0.01
  output_path  : 'model'

# Logging and output parameters
mlflow:
  mlruns_path: 'model'
  tracking_uri: 'http://127.0.0.1:5000'
  experiment_name: 'lstm_dev'
  tags :
    state : "dev"

# Grid search:
hyperparameter_tuning:
  batch_size: [128]
  num_epochs: [20]
  lr: [0.001]
  sequence_len: [10]
  hidden_dim: [64]
  num_layers: [8, 16]