experiment_name: lstm_brk-b_all
model:
  class_path: src.models.LSTM_Lightning.model.StockPricePredictor
  init_args:
    sequence_len: 5
    hidden_dim: 64
    num_layers: 3
    lr: 0.001
    dropout: 0.0
data:
  class_path: src.models.LSTM_Lightning.data.StockDataModule
  init_args:
    stock: "brk-b"
    sequence_len: 5
    batch_size: 64
    permute_column: null
    dataset_len: 5
    horizon: 5 

