# Configuration file for model
# ------------------------------
# Data parameters
model:
   name : 'lstm'
   hidden_dim: 64
   num_layers: 2

data:
  features: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'log_open', 'log_high', 'log_low', 'log_close', 'log_volume',
       'close_t-1', 'close_t-2', 'close_t-3', 'close_t-4',
       'close_t-5', 'pct_change', 'log_return', 'dayofweek', 'quarter',
       'month', 'year', 'dayofyear', 'dayofmonth', 'weekofyear', 'upper_band',
       'middle_band', 'lower_band', 'SMA_3', 'SMA_5', 'SMA_10', 'SMA_20',
       'SMA_50', 'EMA_3', 'EMA_5', 'EMA_10', 'EMA_20', 'EMA_50', 'ADX',
       'aroon_down', 'aroon_up', 'macd', 'macdsignal', 'macdhist', 'RSI_14',
       'slow_k', 'slow_d', 'williams_r', 'AD', 'OBV', 'NATR', 'TRANGE',
       'fed_funds_rate', 'log_fed_funds_rate', '^N225', 'log_^N225', '^IXIC',
       'log_^IXIC', '^FTSE', 'log_^FTSE', '^SPX', 'log_^SPX', '^DJI',
       'log_^DJI']
  sequence_len: 50

# Training parameters
training:
  batch_size: 128
  num_epochs: 50
  lr: 0.01
  output_path  : 'model'

# Logging and output parameters
mlflow:
  mlruns_path: 'models'
  tracking_uri: 'http://127.0.0.1:5000'
  experiment_name: 'lstm_tuning'
  tags :
    state : "dev"

# Grid search:
hyperparameter_tuning:
  batch_size: [64, 128, 256]
  num_epochs: [10, 20, 50]
  lr: [0.1, 0.01, 0.001]
  sequence_len: [3, 5, 10, 20, 50]
  # optimizer: ["Adam"]
  hidden_dim: [32, 64, 124, 256]
  num_layers: [2, 4, 8]