model_name: lstm_lly
fset_name: all
model:
  class_path: src.models.LSTM_Lightning.model.StockPricePredictor
  init_args:
    sequence_len: 20
    hidden_dim: 64
    num_layers: 1
    lr: 0.001
    dropout: 0
data:
  class_path: src.models.LSTM_Lightning.data.StockDataModule
  init_args:
    stock: "lly"
    feature_set: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
      'close_t-1', 'close_t-2', 'close_t-3', 'close_t-4',
       'close_t-5', 'pct_change', 'return', 'dayofweek', 'quarter', 'month',
       'year', 'dayofyear', 'dayofmonth', 'weekofyear', 'upper_band',
       'middle_band', 'lower_band', 'SMA_3', 'SMA_5', 'SMA_10', 'SMA_20',
       'SMA_50', 'EMA_3', 'EMA_5', 'EMA_10', 'EMA_20', 'EMA_50', 'DEMA_3',
       'DEMA_5', 'DEMA_10', 'DEMA_20', 'DEMA_50', 'TEMA_3', 'TEMA_5',
       'TEMA_10', 'TEMA_20', 'TEMA_50', 'ADX', 'aroon_down', 'aroon_up',
       'macd', 'macdsignal', 'macdhist', 'RSI_14', 'slow_k', 'slow_d',
       'williams_r', 'AD', 'OBV', 'NATR', 'TRANGE', 'fed_funds_rate', '^N225',
       '^IXIC', '^FTSE', '^SPX', '^DJI']
    sequence_len: 20
    batch_size: 64
    permute_column: null
    dataset_len: 5
    horizon: 5 

