# Configuration file for model
# ------------------------------
# Data parameters
model:
   hidden_dim: 64
   num_layers: 2

data:
  features: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'close_t-1', 'close_t-2', 'close_t-3', 'close_t-4',
       'close_t-5', 'pct_change', 'return', 'dayofweek', 'quarter', 'month',
       'year', 'dayofyear', 'dayofmonth', 'weekofyear', 'upper_band',
       'middle_band', 'lower_band', 'SMA_3', 'SMA_5', 'SMA_10', 'SMA_20',
       'SMA_50', 'EMA_3', 'EMA_5', 'EMA_10', 'EMA_20', 'EMA_50', 'DEMA_3',
       'DEMA_5', 'DEMA_10', 'DEMA_20', 'DEMA_50', 'TEMA_3', 'TEMA_5',
       'TEMA_10', 'TEMA_20', 'TEMA_50', 'ADX', 'aroon_down', 'aroon_up',
       'macd', 'macdsignal', 'macdhist', 'RSI_14', 'slow_k', 'slow_d',
       'williams_r', 'AD', 'OBV', 'NATR', 'TRANGE', 'fed_funds_rate', '^N225',
       '^IXIC', '^FTSE', '^SPX', '^DJI']
  sequence_len: 5
  stock: "aapl"
  dataset_len: 5

# Training parameters
training:
  batch_size: 128
  num_epochs: 30
  lr: 0.001
  output_path  : 'model'

# Logging and output parameters
mlflow:
  mlruns_path: 'model'
  tracking_uri: 'http://127.0.0.1:5000'
  experiment_name: 'lstm_dev'
  tags :
    state : "dev"

# Grid search:
hyperparameter_tuning:
  batch_size: [128]
  num_epochs: [20]
  lr: [0.001]
  sequence_len: [10]
  hidden_dim: [64]
  num_layers: [8, 16]