seed_everything: 42
trainer:
  max_epochs: 500
  min_epochs: 100
  log_every_n_steps: 1
  enable_model_summary: False
  enable_progress_bar: True
  deterministic: True
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      default_hp_metric: False
      log_graph: True
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: True
        monitor: val_acc
        mode: max
        filename: epoch{epoch:02d}-val_acc{val_acc:.5f}
        auto_insert_metric_name: False
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 100
        verbose: False
        mode: min
        min_delta: 0.000001
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
        log_momentum: True
  