sequence_len: 10
in_channels: 1
out_channels: 30
kernel_size: 10
lr: 0.001
momentum: 0
weight_decay: 0
stock: nvda
feature_set:
- log_return
batch_size: 64
dataset_len: 10
horizon: 5
target_var: log_return_forecast
